language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: JX/JsEzmnvOEc3GVrD5/syVq3KvOoL1gsNeix8AO1dbe7EQvhdepPGcuFvR99gkACRc4apynMp3lk/VmmW6xaxkPFpFY3+/YMQYItjSyBJpGYiKul5LSs7A2n8WTTny9LUoRa66RNHwWU3rMC1RrWb4KshHrid6Ermm5V1Hzd+27LgxiWv49pcuAR+y11JaEnW3P0auc9kcgx7p7YaddnSVxulRhTZyl/FEsoYpQfJpbM3CdiZypxaSMxrOWYNsc2ZoOClHQv7mkzT6eUepO0A4XJ+KOqbhNchjdecKXcYTkCn9USmDBoTCuxeIsQKmgosp0L8U3Q/taPi8NSjVNLQ0WUpK4MhYB/u6dYNvgUeNjI5RSWB4u7L4DDvH/wUX6ncPGiWcyZpzfIIIba/Kb6T9kfwXNMXn8EgEVSEfSzt6XD5bmFudtx4Kp6THTYyOYhNZm1fWwpOG0Pm5XZnzXAU6lxOghzHRkkDH+bRYtNfkzJSFTBDjjAcSlEcKWsLlbCQvSfV6w/AeHEYf9fxqD8DCOdg+zcwIIF06xm9zgW0RXlhmdZAYXSNhBFebUw6+0pXwPcG8OxHuOzOXZMooJemCRgSIIZZMOYVwsnES3s1qyJ2ZOnkF+oaVc+Y7ffV9xJfaZAgkqxP4BjbrojqraG3hWwf13cQ19mju5S7yvFG0=
  app:
  run: rails db:migrate
